spring.application.name=taskflow

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username={DB_USERNAME}
spring.datasource.password={DB_PASSWORD}

spring.jackson.deserialization.fail-on-unknown-properties=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#logging
logging.level.com.thelazydaniel.taskflow.security.permission=DEBUG

# Redis Connection
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password={REDIS_PASSWORD}
spring.data.redis.timeout=2000ms
spring.data.redis.database=0

# Connection Pool
spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=5
spring.data.redis.lettuce.pool.max-wait=2000ms

# Cache Settings
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
spring.cache.redis.key-prefix=app::

# ============ Connection Health ============
spring.data.redis.lettuce.shutdown-timeout=100ms

# ============ Metrics (for monitoring) ============
management.health.redis.enabled=true

# ============ Cache Key Prefixes ==================
security.login.key.user-attempt=login:attempt:user:
security.login.key.ip-attempt=login:attempt:ip:
security.login.key.user-lock=login:lock:user:
security.login.key.ip-block=login:block:ip:

# ======Throttling & Lock Thresholds ===============
security.login.max-attempts=5
security.login.account-lock-minutes=15
security.login.ip-block-minutes=1
security.login.attempt-window-minutes=5

# Rate Limiting Configuration
security.rate-limit.key-prefix=rate:limit:
security.rate-limit.max-requests-per-minute=60
security.rate-limit.request-window-minutes=1

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.jwt.secret=${JWT_SECRET}
app.jwt.refresh-secret=${JWT_REFRESH_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS}




#spring.mvc.servlet.path=/api/v1